events {}
http {
    upstream scheduler {
        server scheduler:8001;
        server scheduler-2:8001;
    }
    upstream node_manager {
        server node-manager:8002;
    }
    server {
        listen 80;
        location /scheduler/ {
            proxy_pass http://scheduler/;
        }
        location /node-manager/ {
            proxy_pass http://node_manager/;
        }
    }
}