events {}
http {
    upstream service_b {
        server service-b:8001;
        server service-b-2:8001;
    }
    upstream service_c {
        server service-c:8002;
    }
    server {
        listen 80;
        location /service-b/ {
            proxy_pass http://service_b/;
        }
        location /service-c/ {
            proxy_pass http://service_c/;
        }
    }
}